CREATE TABLE iscsitargets (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  targetname VARCHAR(1024) NOT NULL,
  description VARCHAR(1024) DEFAULT ''
);

CREATE TABLE initiators (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name VARCHAR(255),
  ipn INTEGER UNSIGNED NOT NULL
);

CREATE TABLE initiators_targets (
  target_id INTEGER,
  initiator_id INTEGER,
  PRIMARY KEY (target_id, initiator_id)
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  login VARCHAR(255) NOT NULL,
  password VARCHAR(32) NOT NULL
);

CREATE TABLE pvs (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  vg_id INTEGER
);

CREATE TABLE vgs (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1024) DEFAULT '',
);

CREATE TABLE lvs (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1024) DEFAULT '',
  gsize INTEGER NOT NULL,
  vg_id INTEGER NOT NULL
);
